name: testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: testing zkauth-sdk
        shell: bash
        run: |
          npm install && npm run lint && npm run test
